vim.cmd("syntax enable")
vim.cmd("set background=dark")
--vim.cmd("colorscheme sonokai")
vim.cmd("colorscheme dracula")
--vim.cmd("colorscheme monokai")
--vim.cmd("colorscheme gruvbox")
--vim.cmd("let g:gruvbox_contrast_dark = 'hard'")
--vim.cmd("colorscheme tokyonight")
--vim.cmd("colorscheme onedark")

require("lualine").setup()
