code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradlc.vscode-tailwindcss
code --install-extension budparr.language-hugo-vscode
code --install-extension calebporzio.better-phpunit
code --install-extension catppuccin.catppuccin-vsc
code --install-extension christian-kohler.path-intellisense
code --install-extension cjhowe7.laravel-blade
code --install-extension codingyu.laravel-goto-view
code --install-extension davidanson.vscode-markdownlint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension ecodes.vscode-phpmd
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension firsttris.vscode-jest-runner
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension golang.go
code --install-extension junstyle.php-cs-fixer
code --install-extension m1guelpf.better-pest
code --install-extension meezilla.json
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension mtxr.sqltools-driver-sqlite
code --install-extension nevyk.draculight
code --install-extension open-southeners.laravel-pint
code --install-extension orta.vscode-jest
code --install-extension shufo.vscode-blade-formatter
code --install-extension this-fifo.natty
code --install-extension twxs.cmake
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension xaver.clang-format
code --install-extension xdebug.php-debug
code --install-extension xdebug.php-pack
